package org.pulp;

public enum TokenType {

    // single character tokens
    COMMA, DOT, COLON, EOF,

    // Single word keywords
    CONSTANT, LET,
    IDENTIFIER,
    INVOKE,
    SHOULD, THEN, OTHERWISE,
    ADD, REMOVE, MULTIPLY, DIVIDE,
    TO, FROM, WITH, BY,

    //Multi word keywords
    TYPE_WHOLE_NUMBER, TYPE_REAL_NUMBER, TYPE_STRING, TYPE_TRUTH_VALUE,
    INTEGER_LITERAL, REAL_LITERAL, BOOLEAN_LITERAL, STRING_LITERAL,
    IS_EQUAL_TO, BE_EQUAL_TO,
    DISPLAY_RESULT,
    INPUT_FROM_USER,
    WITH_COLON,
    REPEAT_UNTIL,
    DESCRIPTION_OF_A_SUBPROGRAM_CALLED, ACTING_ON_INPUTS, THUS_PRODUCING_OUTPUTS,
    LESS_THAN,
    LESS_OR_EQUAL_THAN,
    MORE_THAN,
    MORE_OR_EQUAL_THAN,
    EQUAL_TO,
}
